// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_memegen from "./routes/api/memegen.ts";
import * as $api_memes from "./routes/api/memes.ts";
import * as $api_swap from "./routes/api/swap.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $SwapForm from "./islands/SwapForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/memegen.ts": $api_memegen,
    "./routes/api/memes.ts": $api_memes,
    "./routes/api/swap.ts": $api_swap,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/SwapForm.tsx": $SwapForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
